<?php
/**
 * Shared install/import routines used by BOTH the command-line tools (bin/*)
 * and the browser installer (public/setup.php). Every function returns a
 * short result array so the caller can print it (CLI) or render it (web).
 */
require_once __DIR__ . '/db.php';

/** Write config.php from an array of settings (merged over the example defaults). */
function write_config(array $settings) {
    $base = require __DIR__ . '/../config.example.php';
    $cfg = array_merge($base, $settings);
    $php = "<?php\n/** Generated by the installer. */\nreturn " . var_export($cfg, true) . ";\n";
    $file = __DIR__ . '/../config.php';
    if (file_put_contents($file, $php) === false) return [false, "Could not write config.php — check folder permissions."];
    return [true, "config.php written."];
}

/** Create every table (driver-aware). Safe to re-run. */
function install_migrate() {
    $driver = db_driver();
    $AI  = $driver === 'sqlite' ? 'INTEGER PRIMARY KEY AUTOINCREMENT' : 'INT AUTO_INCREMENT PRIMARY KEY';
    $ENG = $driver === 'sqlite' ? '' : ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';
    $tables = [
"users" => "CREATE TABLE IF NOT EXISTS users (
  id $AI, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(40) DEFAULT '',
  pass_hash VARCHAR(255) DEFAULT '', role VARCHAR(20) NOT NULL DEFAULT 'member',
  status VARCHAR(20) NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_login TIMESTAMP NULL
)$ENG",
"invites" => "CREATE TABLE IF NOT EXISTS invites (
  id $AI, token VARCHAR(64) NOT NULL, name VARCHAR(120) DEFAULT '', email VARCHAR(190) DEFAULT '',
  role VARCHAR(20) NOT NULL DEFAULT 'member', invited_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP NULL, used_at TIMESTAMP NULL
)$ENG",
"persons" => "CREATE TABLE IF NOT EXISTS persons (
  pid VARCHAR(16) PRIMARY KEY, name VARCHAR(200) DEFAULT '', given VARCHAR(160) DEFAULT '', surname VARCHAR(120) DEFAULT '',
  sex VARCHAR(4) DEFAULT '', birth_date VARCHAR(80) DEFAULT '', birth_place VARCHAR(200) DEFAULT '',
  death_date VARCHAR(80) DEFAULT '', death_place VARCHAR(200) DEFAULT '', buri_date VARCHAR(80) DEFAULT '', buri_place VARCHAR(200) DEFAULT '',
  living INT DEFAULT 0, famc TEXT, fams TEXT, occupation TEXT, education TEXT, notes TEXT
)$ENG",
"families" => "CREATE TABLE IF NOT EXISTS families (
  fid VARCHAR(16) PRIMARY KEY, husb VARCHAR(16) DEFAULT '', wife VARCHAR(16) DEFAULT '',
  marr_date VARCHAR(80) DEFAULT '', marr_place VARCHAR(200) DEFAULT '', chil TEXT
)$ENG",
"photos" => "CREATE TABLE IF NOT EXISTS photos (
  id $AI, pid VARCHAR(16) NOT NULL, filename VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL,
  caption VARCHAR(500) DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'approved',
  source VARCHAR(20) NOT NULL DEFAULT 'import', uploaded_by INT NULL, is_primary INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)$ENG",
    ];
    foreach ($tables as $sql) db()->exec($sql);
    foreach ([
      "CREATE INDEX idx_photos_pid ON photos(pid)","CREATE INDEX idx_photos_status ON photos(status)",
      "CREATE INDEX idx_users_email ON users(email)","CREATE INDEX idx_invites_token ON invites(token)",
      "CREATE INDEX idx_persons_surname ON persons(surname)",
    ] as $s) { try { db()->exec($s); } catch (Exception $e) {} }
    return ['driver' => $driver, 'tables' => array_keys($tables)];
}

// ---------- GEDCOM ----------
function _ged_read_event($lines, $start, $N) {
    $L = $lines[$start][0]; $j = $start + 1; $date = $place = '';
    while ($j < $N && $lines[$j][0] > $L) { [$lvl,,$tag,$val] = $lines[$j];
        if ($lvl === $L+1 && $tag === 'DATE') $date = $val; elseif ($lvl === $L+1 && $tag === 'PLAC') $place = $val; $j++; }
    return [$date, $place, $j];
}
function _ged_read_note($lines, $start, $N) {
    $L = $lines[$start][0]; $text = $lines[$start][3]; $j = $start + 1;
    while ($j < $N && $lines[$j][0] > $L) { [$lvl,,$tag,$val] = $lines[$j];
        if ($lvl === $L+1 && $tag === 'CONC') $text .= $val; elseif ($lvl === $L+1 && $tag === 'CONT') $text .= "\n".$val; $j++; }
    $text = preg_replace('/<br\s*\/?>/i', "\n", $text);
    return [trim(preg_replace('/\n{3,}/', "\n\n", $text)), $j];
}
function install_gedcom($path) {
    if (!is_file($path)) return ['ok' => false, 'error' => "GEDCOM file not found: $path"];
    $raw = preg_split('/\r\n|\r|\n/', file_get_contents($path));
    $lines = [];
    foreach ($raw as $ln) {
        if (trim($ln) === '') continue;
        if (!preg_match('/^(\d+)\s+(@[^@]+@)?\s*([A-Z0-9_]+)?\s?(.*)$/', $ln, $m)) continue;
        $lines[] = [(int)$m[1], $m[2] ?: '', $m[3] ?: '', trim($m[4] ?? '')];
    }
    $N = count($lines); $indi = []; $fam = []; $i = 0;
    while ($i < $N) {
        [$level, $xref, $tag] = $lines[$i];
        if ($level === 0 && $xref && $tag === 'INDI') {
            $pid = $xref;
            $r = ['id'=>$pid,'name'=>'','given'=>'','surname'=>'','sex'=>'','birth'=>['',''],'death'=>['',''],'buri'=>['',''],'occupation'=>[],'education'=>[],'notes'=>[],'famc'=>[],'fams'=>[]];
            $i++;
            while ($i < $N && $lines[$i][0] !== 0) {
                [$lvl,,$t,$v] = $lines[$i];
                if ($t==='NAME' && $lvl===1) {
                    /* GEDCOM writes "Augustus /Battles/ Jr." — the surname is between
                       the slashes and anything after it is a suffix. The old pattern
                       swallowed the closing slash into the surname, which is why 59
                       people were displayed as "Augustus Battles/ Jr." */
                    if (preg_match('~^(.*?)/([^/]*)/(.*)$~', $v, $gm)) {
                        $r['given']=trim($gm[1]); $r['surname']=trim($gm[2]);
                        $sfx=trim($gm[3]);
                        $r['name']=trim($r['given'].' '.$r['surname'].($sfx!=='' ? ' '.$sfx : ''));
                    }
                    else { $r['name']=trim($v); $r['given']=trim($v); }
                } elseif ($t==='SEX' && $lvl===1) { $r['sex']=substr(trim($v),0,1);
                } elseif ($t==='BIRT' && $lvl===1) { [$d,$p,$nx]=_ged_read_event($lines,$i,$N); $r['birth']=[$d,$p]; $i=$nx; continue;
                } elseif ($t==='DEAT' && $lvl===1) { [$d,$p,$nx]=_ged_read_event($lines,$i,$N); $r['death']=[$d,$p]; $i=$nx; continue;
                } elseif ($t==='BURI' && $lvl===1) { [$d,$p,$nx]=_ged_read_event($lines,$i,$N); $r['buri']=[$d,$p]; $i=$nx; continue;
                } elseif ($t==='OCCU' && $lvl===1 && trim($v)!=='') { $r['occupation'][]=trim($v);
                } elseif ($t==='EDUC' && $lvl===1 && trim($v)!=='') { $r['education'][]=trim($v);
                } elseif ($t==='NOTE' && $lvl===1) { [$txt,$nx]=_ged_read_note($lines,$i,$N); if($txt)$r['notes'][]=$txt; $i=$nx; continue;
                } elseif ($t==='FAMC' && $lvl===1) { $r['famc'][]=trim($v);
                } elseif ($t==='FAMS' && $lvl===1) { $r['fams'][]=trim($v); }
                $i++;
            }
            if ($r['name']==='') $r['name']='Unknown';
            $indi[$pid]=$r;
        } elseif ($level === 0 && $xref && $tag === 'FAM') {
            $fid=$xref; $r=['husb'=>'','wife'=>'','chil'=>[],'marr'=>['','']]; $i++;
            while ($i < $N && $lines[$i][0] !== 0) {
                [$lvl,,$t,$v]=$lines[$i];
                if ($t==='HUSB'&&$lvl===1) $r['husb']=trim($v); elseif ($t==='WIFE'&&$lvl===1) $r['wife']=trim($v);
                elseif ($t==='CHIL'&&$lvl===1) $r['chil'][]=trim($v);
                elseif ($t==='MARR'&&$lvl===1) { [$d,$p,$nx]=_ged_read_event($lines,$i,$N); $r['marr']=[$d,$p]; $i=$nx; continue; }
                $i++;
            }
            $fam[$fid]=$r;
        } else { $i++; }
    }
    $by = function($d) { return preg_match('/\d{4}/',$d,$m) ? (int)$m[0] : null; };
    db()->beginTransaction();
    db()->exec("DELETE FROM persons"); db()->exec("DELETE FROM families");
    $living = 0;
    $ins = db()->prepare("INSERT INTO persons (pid,name,given,surname,sex,birth_date,birth_place,death_date,death_place,buri_date,buri_place,living,famc,fams,occupation,education,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    foreach ($indi as $pid=>$r) {
        $deceased = trim($r['death'][0]) !== ''; $yy = $by($r['birth'][0]);
        $isLiving = (!$deceased) && ($yy === null || $yy > 1935); if ($isLiving) $living++;
        $ins->execute([$pid,$r['name'],$r['given'],$r['surname'],$r['sex'],$r['birth'][0],$r['birth'][1],$r['death'][0],$r['death'][1],$r['buri'][0],$r['buri'][1],
            $isLiving?1:0, json_encode($r['famc']),json_encode($r['fams']),json_encode($r['occupation']),json_encode($r['education']),json_encode($r['notes'])]);
    }
    $insf = db()->prepare("INSERT INTO families (fid,husb,wife,marr_date,marr_place,chil) VALUES (?,?,?,?,?,?)");
    foreach ($fam as $fid=>$r) $insf->execute([$fid,$r['husb'],$r['wife'],$r['marr'][0],$r['marr'][1],json_encode($r['chil'])]);
    db()->commit();
    return ['ok' => true, 'individuals' => count($indi), 'families' => count($fam), 'living' => $living];
}

// ---------- Photos ----------
function _norm($s) { $s = strtolower($s); $s = str_replace(['`',"'",'"','.'], '', $s); return trim(preg_replace('/\s+/',' ', preg_replace('/[^a-z0-9]+/',' ',$s))); }
function _clean_filename($base) {
    $b = preg_replace('/^thumb[_ ]+/i','',$base);          // strip thumbnail prefix
    $b = preg_replace('/\[\d+\]/','',$b); $b = preg_replace('/\([^)]*\)/','',$b);
    $b = preg_replace('/[_]+/',' ',$b); $b = preg_replace('/\s*\d+\s*$/','',$b);
    return trim(preg_replace('/\s+/',' ',$b));
}
function _first_last($name, $SUFFIX) {
    $t = array_values(array_filter(explode(' ', _norm($name)), function($w) use ($SUFFIX) { return !in_array($w,$SUFFIX,true); }));
    return count($t) < 2 ? null : $t[0].' '.end($t);
}
function install_photos($srcDir, $dry = false, $opts = []) {
    if (!is_dir($srcDir)) return ['ok' => false, 'error' => "Photo folder not found: $srcDir"];
    $offset = max(0, (int)($opts['offset'] ?? 0));
    $limit  = max(0, (int)($opts['limit']  ?? 0));   // 0 = the lot
    $SUFFIX = ['sr','jr','ii','iii','iv','v'];
    $OVERRIDES = [
        'anothany wynn'=>'@I252@', 'agustus battles'=>'@I35@',
        'gus battles'=>'@I35@',      // Augustus `Gus` Battles
        'horatio'=>'@I29@',          // Horatio Battles (unique)
        'cos battles'=>'@I104@',     // Costromia `Cos` Battles
        'fred battles'=>'@I49@',     // Frederick `Fred` Lee Battles
        'chris holmes'=>'@I2@',      // Christopher Steele Holmes
        'chic chandler'=>'@I726@',   // Shertoddra `Chic` Chandler
        'frank fristoe'=>'@I789@',   // Benjamin Franklin (Frank) Fristoe
        // spelling / nickname / married-name variants confirmed against the tree
        'dianne battles'=>'@I13@',   // Dianna Battles
        'fabin thomas'=>'@I710@',    // Fabian Thomas
        'darly phillips'=>'@I57@',   // Daryll Phillips
        'patrica holmes'=>'@I17@',   // Patricia Ann Holmes
        'james batles'=>'@I11@',     // James Earl Battles (misspelled file)
        'cleo mclendon'=>'@I773@',   // Cleopatra McClendon
        'cindi ward'=>'@I476@',      // Cinda J. Ward
        'hannah'=>'@I474@',          // Hannah Lauren Richmond
        'meagan'=>'@I711@',          // Meagan Olivia Richmond
        'rory'=>'@I108@',            // Rory Micah Richmond
        'nathaniel battles tomb'=>'@I39@',  // Nathaniel Battles (grave photo)
        'gus battles headstone'=>'@I35@',   // Augustus `Gus` Battles (grave photo)
        // Married names and nicknames, each confirmed against the tree rather
        // than guessed — a wrong face on a relative's page is worse than none.
        'jt battles'=>'@I7@',        // James `JT` Thomas Battles
        'jing nicholson'=>'@I721@',  // Jing Purcell Nourse, married Darius Nicholson
        'marjorie hobson'=>'@I506@', // Marjorie Fristoe, married Henry Hobson Sr
        'barbara battles'=>'@I230@', // Barbara Moore, married James Earl Battles
        'annie fristoe'=>'@I790@',   // Margaret Anne (Annie) Spence, married Frank Fristoe
        'ladonica williams'=>'@I706@', // La Donica Janelle Williams (the file closes the space)
        // Group photographs pin to the first person named; the caption keeps
        // every name, so the others are still findable.
        'brian chic'=>'@I28@',          // Brian Holmes & Shertoddra `Chic` Chandler
        'hannah meagan'=>'@I474@',      // Hannah Lauren Richmond
        'meagan hannah'=>'@I711@',      // Meagan Olivia Richmond
        'meagan rory hannah'=>'@I711@',
        'rory hannah meagan'=>'@I108@', // Rory Micah Richmond
    ];
    $people = all("SELECT pid,name,given,surname FROM persons");
    $byFull=[]; $byFL=[]; $byGiven=[];
    foreach ($people as $p) {
        $full=_norm($p['name']);
        if ($full!=='' && !isset($byFull[$full])) $byFull[$full]=$p['pid'];
        $fl=_first_last($p['name'],$SUFFIX); if ($fl && !isset($byFL[$fl])) $byFL[$fl]=$p['pid'];
        $g=_norm($p['given']);
        if ($g!=='' && strpos($g,' ')!==false) { if (isset($byGiven[$g]) && $byGiven[$g]!==$p['pid']) $byGiven[$g]=null; elseif (!array_key_exists($g,$byGiven)) $byGiven[$g]=$p['pid']; }
    }
    $match = function($cleanName) use ($SUFFIX,$OVERRIDES,$byFull,$byFL,$byGiven) {
        $n=_norm($cleanName);
        if (isset($OVERRIDES[$n])) return $OVERRIDES[$n];
        if (isset($byFull[$n])) return $byFull[$n];
        $t=explode(' ',$n);
        if (count($t)>2 && in_array(end($t),$SUFFIX,true)) { array_pop($t); $n2=implode(' ',$t); if (isset($byFull[$n2])) return $byFull[$n2]; }
        $fl=_first_last($cleanName,$SUFFIX); if ($fl && isset($byFL[$fl])) return $byFL[$fl];
        if (!empty($byGiven[$n])) return $byGiven[$n];
        return null;
    };
    $publicDir = __DIR__ . '/../public/';
    if (!$dry) @mkdir($publicDir . config('photos_dir'), 0775, true);
    $exts=['jpg','jpeg','png','gif','webp']; $full=[]; $thumb=[];
    foreach (scandir($srcDir) as $f) {
        if ($f[0]==='.') continue;
        if (!in_array(strtolower(pathinfo($f,PATHINFO_EXTENSION)),$exts,true)) continue;
        if (preg_match('/^thumb[_ ]/i',$f)) $thumb[]=$f; else $full[]=$f;
    }
    sort($full); sort($thumb);
    // Full-size photos first; then thumbnails ONLY for people who still have no photo
    // (so we never duplicate, but people whose pictures exist only as thumbnails still get them).
    $files = array_merge($full, $thumb);
    $isThumb = array_fill_keys($thumb, true);
    $total = count($files);
    if ($offset || $limit) $files = array_slice($files, $offset, $limit ?: null);

    $stats=['matched'=>0,'copied'=>0,'skipped'=>0,'unmatched'=>0,'thumb_used'=>0,'thumb_redundant'=>0,
            'duplicate'=>0,'bytes'=>0]; $unmatched=[];
    $havePhoto=[]; foreach (all("SELECT DISTINCT pid FROM photos") as $r) $havePhoto[$r['pid']]=true;

    /* The same picture is in that folder several times over — "Amy Battles 1.jpg",
       "Amy Battles 1 (1).jpg", "Amy Battles 1 (2).jpg" are byte for byte identical.
       Matching on the file NAME would put each of them on her page as a separate
       photograph, so the test is the CONTENT: one hash per person, and a second
       copy of a picture she already has is skipped. */
    $seen = [];
    foreach (all("SELECT pid, path FROM photos") as $r) {
        $abs = $publicDir . $r['path'];
        if (is_file($abs)) $seen[$r['pid'] . '|' . md5_file($abs)] = true;
    }

    $exists = db()->prepare("SELECT id FROM photos WHERE pid=? AND filename=?");
    $insert = db()->prepare("INSERT INTO photos (pid,filename,path,caption,status,source) VALUES (?,?,?,?, 'approved','import')");
    foreach ($files as $f) {
        $cleanName=_clean_filename(pathinfo($f,PATHINFO_FILENAME));
        $pid=$match($cleanName);
        if (!$pid) { $stats['unmatched']++; $unmatched[]=$f; continue; }
        if (!empty($isThumb[$f]) && !empty($havePhoto[$pid])) { $stats['thumb_redundant']++; continue; } // person already has a real photo
        $src = $srcDir.'/'.$f;
        $hash = @md5_file($src);
        $key  = $pid . '|' . $hash;
        if ($hash === false) { $stats['unmatched']++; $unmatched[]=$f.' (unreadable)'; continue; }
        if (isset($seen[$key])) { $stats['duplicate']++; $havePhoto[$pid]=true; continue; }
        $stats['matched']++;
        if (!empty($isThumb[$f])) $stats['thumb_used']++;
        $stats['bytes'] += (int)@filesize($src);
        $safe=preg_replace('/[^A-Za-z0-9._-]+/','_',$f);
        $relDir=config('photos_dir').'/'.trim($pid,'@'); $rel=$relDir.'/'.$safe;
        $exists->execute([$pid,$f]); if ($exists->fetch()) { $stats['skipped']++; $havePhoto[$pid]=true; $seen[$key]=true; continue; }
        if (!$dry) {
            @mkdir($publicDir.$relDir,0775,true); if (@copy($src,$publicDir.$rel)) $stats['copied']++;
            $insert->execute([$pid,$f,$rel,$cleanName]);
            /* Also record who is in it. On a first-ever import the tagging table
               doesn't exist yet and is backfilled when it is created, so this is
               only load-bearing for a re-import onto a site already running. */
            require_once __DIR__ . '/photo_people.php';
            pp_tag((int)insert_id(), $pid);
        }
        $havePhoto[$pid]=true; $seen[$key]=true;
    }
    return ['ok' => true, 'stats' => $stats, 'unmatched' => $unmatched,
            'total' => $total, 'offset' => $offset, 'done' => ($offset + count($files)) >= $total];
}

// ---------- Admin ----------
function install_admin($name, $email, $pass) {
    $email = strtolower(trim($email));
    if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL) || strlen($pass) < 8)
        return ['ok' => false, 'error' => 'Need a name, a valid email, and an 8+ character password.'];
    $hash = password_hash($pass, PASSWORD_DEFAULT);
    $ex = one("SELECT id FROM users WHERE email=?", [$email]);
    if ($ex) q("UPDATE users SET name=?, pass_hash=?, role='admin', status='active' WHERE id=?", [$name,$hash,$ex['id']]);
    else q("INSERT INTO users (name,email,pass_hash,role,status) VALUES (?,?,?, 'admin','active')", [$name,$email,$hash]);
    return ['ok' => true, 'email' => $email];
}

/** One-off tidy-up for people imported before the NAME parser was fixed:
 *  the closing GEDCOM slash was left glued to the surname, so a suffix came
 *  out as "Battles/ Jr." instead of "Battles Jr.". Only touches rows that
 *  still carry a slash, so it is safe to run again. */
function install_fix_slashed_names($apply = false) {
    $out = [];
    foreach (all("SELECT pid,name,given,surname FROM persons WHERE name LIKE '%/%' OR surname LIKE '%/%'") as $p) {
        $sur = (string)$p['surname'];
        $sfx = '';
        if (strpos($sur, '/') !== false) {
            list($sur, $sfx) = array_map('trim', explode('/', $sur, 2));
        }
        $name = trim(trim((string)$p['given']) . ' ' . $sur . ($sfx !== '' ? ' ' . $sfx : ''));
        $name = trim(preg_replace('/\s+/', ' ', str_replace('/', ' ', $name)));
        if ($name === '' || ($name === $p['name'] && $sur === $p['surname'])) continue;
        $out[] = ['pid' => $p['pid'], 'from' => $p['name'], 'to' => $name];
        if ($apply) q("UPDATE persons SET name=?, surname=? WHERE pid=?", [$name, $sur, $p['pid']]);
    }
    return $out;
}
